apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-configmap
data:
  kong-config.yaml: |
    _format_version: "2.1"
    services:
      - name: backend-api
        url: http://saytruth-service:8000
        routes:
          - name: backend-api-route
            paths:
              - /api
