apiVersion: v1
kind: Secret
metadata:
  name: saytruth-secrets
type: Opaque
stringData:
  # JWT & AUTHENTICATION
  JWT_SECRET: "Z6BkzaWcF7r5cC-VMAumjpBpudSyjGskQ0ObquGJhG0="
  ENCRYPTION_KEY: "Vv3oE5-p_z1rM3DqK_u_M-7yY_X8z3R_L_k9wB-nS8E="